name: Auto approve PRs

on:
  pull_request_target:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
